language: android
android:
  components:
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23
    - build-tools-23.0.1
    - extra-google-google_play_services
    - addon-google_apis-google-23
